<a href="https://colab.research.google.com/github/AnshumanAI/ML_Once_Again/blob/main/KNN_on_Iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#On Iris dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from sklearn import datasets

In [ ]:
Iris=datasets.load_iris()
X = Iris.data[:, :3]
y = Iris.target

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
for I in range(1,11):
    KNN=KNeighborsClassifier(n_neighbors=I)
    KNN.fit(x_train,y_train)
    Prediction=KNN.predict(x_test)
    print("accuracy for k=",I,"is",accuracy_score(y_test,Prediction))
    print("confusion matrix::\n",confusion_matrix(y_test, Prediction))

accuracy for k= 1 is 0.8333333333333334
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  4  9]]
accuracy for k= 2 is 0.8
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  5  8]]
accuracy for k= 3 is 0.8666666666666667
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  3 10]]
accuracy for k= 4 is 0.8333333333333334
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  4  9]]
accuracy for k= 5 is 0.8333333333333334
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  4  9]]
accuracy for k= 6 is 0.8333333333333334
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  4  9]]
accuracy for k= 7 is 0.9
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  2 11]]
accuracy for k= 8 is 0.8333333333333334
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  4  9]]
accuracy for k= 9 is 0.8666666666666667
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  3 10]]
accuracy for k= 10 is 0.8333333333333334
confusion matrix::
 [[11  0  0]
 [ 0  5  1]
 [ 0  4  9]]


In [ ]:
#optimal value of k is k=7

In [ ]:
#https://colab.research.google.com/drive/1u6uPjZ-UOhuOXcg_sTHoWPxAjlEDgphc#scrollTo=NBkjWaU3rPhN