<a href="https://colab.research.google.com/github/AnshumanAI/ML_Once_Again/blob/main/Lab_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
from sklearn import datasets
import pandas as pd
import numpy as np
#importing modules,packages and libraries

In [ ]:
Iris=datasets.load_iris()
X = Iris.data[:, :3]
y = Iris.target
#This might give independent and dependent variable lists

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.svm import SVC
model=SVC()
#Gives a support vector classifier,SVC ig

In [ ]:
model.fit(x_train, y_train)

SVC()

In [ ]:
predictions_yhat=model.predict(x_test)
print(predictions_yhat)

[1 2 1 1 1 1 0 1 2 2 2 2 1 0 0 1 2 2 0 1 0 1 0 0 1 1 2 1 1 1]


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, predictions_yhat))

[[ 7  0  0]
 [ 0 13  0]
 [ 0  2  8]]


In [ ]:
print(classification_report(y_test, predictions_yhat))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.87      1.00      0.93        13
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.96      0.93      0.94        30
weighted avg       0.94      0.93      0.93        30




_written by Anshuman Awasthi_

True positives for 0 are the only positives for class 0.
For class 1,13 true positives and 2 false positives.
For class 2,out of 8 predictions 8 are true positives making the precision 1.00

In [ ]:
#comparative analysis of kernels
from sklearn.metrics import accuracy_score
model_kernel_linear = SVC(kernel='linear')
model_kernel_linear.fit(x_train, y_train)
Yhat_linear = model_kernel_linear.predict(x_test)
print('Accuracy score - Linear Kernel: ', round(accuracy_score(y_test, Yhat_linear),3))

model_kernel_polynomial = SVC(kernel='poly')
model_kernel_polynomial.fit(x_train, y_train)
Yhat_poly = model_kernel_polynomial.predict(x_test)
print('Accuracy score - Poly Kernel: ', round(accuracy_score(y_test, Yhat_poly),3))

model_kernel_rbf= SVC(kernel='rbf')
model_kernel_rbf.fit(x_train, y_train)
Yhat_rbf = model_kernel_rbf.predict(x_test)
print('Accuracy score - RBF Kernel: ', round(accuracy_score(y_test, Yhat_rbf),3))

Accuracy score - Linear Kernel:  0.933
Accuracy score - Poly Kernel:  0.967
Accuracy score - RBF Kernel:  0.933


In [ ]:
#Trying with more test cases
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test=train_test_split(X,y,test_size=0.3)

In [ ]:
from sklearn.metrics import accuracy_score
model_kernel_linear = SVC(kernel='linear')
model_kernel_linear.fit(x_train, y_train)
Yhat_linear = model_kernel_linear.predict(x_test)
print('Accuracy score - Linear Kernel: ', round(accuracy_score(y_test, Yhat_linear),3))

model_kernel_polynomial = SVC(kernel='poly')
model_kernel_polynomial.fit(x_train, y_train)
Yhat_poly = model_kernel_polynomial.predict(x_test)
print('Accuracy score - Poly Kernel: ', round(accuracy_score(y_test, Yhat_poly),3))

model_kernel_rbf= SVC(kernel='rbf')
model_kernel_rbf.fit(x_train, y_train)
Yhat_rbf = model_kernel_rbf.predict(x_test)
print('Accuracy score - RBF Kernel: ', round(accuracy_score(y_test, Yhat_rbf),3))

Accuracy score - Linear Kernel:  0.956
Accuracy score - Poly Kernel:  0.933
Accuracy score - RBF Kernel:  0.978


In [ ]:
"""note for self ig

accuracy increased with less number of training examples for 2 out of 3 kernels, perhaps indicating a prior overfitting??

Or just picking of rows?"""

'note for self ig\n\naccuracy increased with less number of training examples for 2 out of 3 kernels, perhaps indicating a prior overfitting??\n\nOr just picking of rows?'

In [ ]:
#https://colab.research.google.com/drive/1onlzbXtMN4qDcyZLsmKg2hkcwOQd2_yO#scrollTo=o8kwBhLAW_zW

In [ ]:
#On diabetes dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
!ls

drive  sample_data


In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/Copy of diabetes.csv")
df2 = df1.copy()

In [ ]:
df2.shape
df2.head()
df2.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_0, *['Pregnancies'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_1, *['Glucose'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_2, *['BloodPressure'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_3, *['SkinThickness'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_4, *['Pregnancies'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_5, *['Glucose'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_6, *['BloodPressure'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_7, *['SkinThickness'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plots(df, colname_pairs, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * 6 * figscale, 6 * figscale))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha, ax=ax)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(_df_8, *[[['Pregnancies', 'Glucose'], ['Glucose', 'BloodPressure'], ['BloodPressure', 'SkinThickness'], ['SkinThickness', 'Insulin']]], **{})
chart

In [ ]:
#Checking for missing values.
df2.isnull().values.any()

False

In [ ]:
zeroless = ["Glucose","BloodPressure","SkinThickness"]

for column in zeroless:
    df2[column] = df2[column].replace(0, np.NaN)
    mean = int(df2[column].mean(skipna = True))
    df2[column] = df2[column].replace(np.NaN, mean)

In [ ]:
 #Splitting the dataset into training and testing sets.
from sklearn.model_selection import train_test_split
x = df2.iloc[:, :-2]
y = df2.iloc[:, -1]
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0, test_size = 0.2)

In [ ]:
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score
model_kernel_linear = SVC(kernel='linear')
model_kernel_linear.fit(x_train, y_train)
Yhat_linear = model_kernel_linear.predict(x_test)
print('Accuracy score - Linear Kernel: ', round(accuracy_score(y_test, Yhat_linear),3))

model_kernel_polynomial = SVC(kernel='poly')
model_kernel_polynomial.fit(x_train, y_train)
Yhat_poly = model_kernel_polynomial.predict(x_test)
print('Accuracy score - Poly Kernel: ', round(accuracy_score(y_test, Yhat_poly),3))

model_kernel_rbf= SVC(kernel='rbf')
model_kernel_rbf.fit(x_train, y_train)
Yhat_rbf = model_kernel_rbf.predict(x_test)
print('Accuracy score - RBF Kernel: ', round(accuracy_score(y_test, Yhat_rbf),3))

Accuracy score - Linear Kernel:  0.805
Accuracy score - Poly Kernel:  0.786
Accuracy score - RBF Kernel:  0.792
